# Generated by Django 5.0.4 on 2024-04-12 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_limit_alter_event_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_1', to='events.eventcategory')),
                ('interest_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_2', to='events.eventcategory')),
                ('interest_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_3', to='events.eventcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
